### ISSUE TITLE
about accuracy

### ISSUE THREAD

**Issue by akziq** [FesianXu/PLSTM#2]
The paper hold that they had achieving 62.93% and 70.27% of top-1 error.
 Can we achieve this result?

**Comment by FesianXu** [comment]
@akziq
in the cross subject evaluation, i just reach to roughly 58% without any fine-tuning and i have not done the cross view evaluation.Maybe the accuracy could be better if we fine tune well.

**Comment by FesianXu** [comment]
@akziq
also, i am not very sure i have the same processing discribed in the origin paper. Maybe it made bias in result.

**Comment by akziq** [comment]
thanks for your response.I will try it.
