### ISSUE TITLE
Regarding the Config file used in PLSTM_xsub.ipynb

### ISSUE THREAD

**Issue by Anirudh257** [FesianXu/PLSTM#6]
Hey, I am trying to run the **PLSTM_xsub** notebook but I am unable to get the configuration file for running it. Specifically, I am unable to run the code given in line 2:

>from codes.GlobalConfig import mGlobalConfig
>gc = mGlobalConfig.GlobalConfig()

Can you provide the **codes** folder required to run the notebook? I want to run the notebook and try to reproduce the results.

Thanks.

**Comment by FesianXu** [comment]
I coded this a year ago and the configuration file was lost now. I will try to search the file but I'm not sure whether I can find it. In fact, the file is quite simple, just some configuration about the model saving path and model loading path, the number of the actions, the number of the joints e.t.c. Thus i think maybe you can try to code your own config file. Usually, it can also work.
Sorry for my carelessness

**Comment by Anirudh257** [comment]
No, problem. I will try it myself and get back to you if I have any doubts.
