### ISSUE TITLE
How do you train the PLSTM model?

### ISSUE THREAD

**Issue by HARFIE** [FesianXu/PLSTM#9]
I downgraded python 3.8 to 3.7 in order to install tensorflow 1.14 so that it has the tf.contrib module.

I have the skeleton data ready to feed to the model, but how do you do it? since  the class PLSTM doesn't have a fit method like the others models in keras tensorflow

**Comment by FesianXu** [comment]
I had written a simple training procedure at https://github.com/FesianXu/PLSTM/blob/master/app/PLSTM_xsub.ipynb
